### ISSUE TITLE
Disable jailbreak detection

### ISSUE THREAD

**Issue by acalatrava** [RadarCOVID/radar-covid-ios#12]
There is a jailbreak detection in place which I don't understand the purpose of. Jailbreak detection should be disabled to work in as many devices as possible (in fact, I'm not using it because of this issue)

If jailbreak detection is mandatory please explain why.

**Comment by jorgej-ramos** [comment]
I kindly disagree. Jailbroken devices are not officially supported and therefore do not offer guarantees of correct operation.

Although other implementations such as CoronaWarn seem to allow the use of jailbroken terminals, it can lead to malfunctions. There are some discussions about it:

https://github.com/corona-warn-app/cwa-app-ios/issues/924
https://github.com/corona-warn-app/cwa-app-ios/issues/823

If this is the case, supporting jailbroken terminals can become an operational problem.
However, it seems like an interesting topic to discuss.

**Comment by acalatrava** [comment]
I understand your point but I don't think it will cause a lot of problems. Most of the users that jailbreak their devices, specially nowadays, are power users that want to add new features to their devices. Some tweaks may interfere with the correct operation of some apps but this won't happen very often.

Out of the two links you pointed only one of them seems to be related to a jailbreak issue, and it's because the user deliberately manipulate the internal sqlite database of the app... 

The solution to me is to not offer support to jailbroken devices, period. This is enough for me and I will understand it. What I do not understand is to detect if the device is jailbroken and stop the app at all... I could understand this behaviour in games where you can cheat, but not on this kind of apps.

**Comment by jorgej-ramos** [comment]
I understand your argument and it seems valid to me. In any case, and specifying in RadarCOVID, I think that the key can be found in the way of working in consulting, and certain pre-established rules.

With pre-established rules I refer to certain items such as the inclusion of RxSwift or Alamofire, unnecessary dependencies from my point of view and of course, the non-acceptance of jailbroken devices.

This all sounds like a predefined project outline to me, but of course I could be wrong. I don't judge it, I just convey my impression.
Nice conversation, by the way.

**Comment by acalatrava** [comment]
Yes, I'm pretty sure that's the "problem" with this... they probably add this jailbreak-detection file to all the projects they do to just "cover their asses" ;)

Yep! Nice to meet you!

**Comment by gmoraleda** [comment]
Jailbroken devices allow users to access system files outside the iOS sandbox. This app deals with cryptographic keys and therefore makes total sense avoiding jailbroken devices to use it. Keys could get modified/corrupted and afterward uploaded to the database.

**Comment by pvieito** [comment]
@gmoraleda All client code should be always considered compromised (ie. you can easily skip the current check on a jailbroken device using `lldb` or even directly recompile the binary from the public source code as you can use restricted entitlements!). The way to enforce the keys validation, is server-side (which is already done), checking that the one-time code is valid and that only 14 TEKs at maximum are sent.

**Comment by javimurcia** [comment]
> 
> 
> Jailbroken devices allow users to access system files outside the iOS sandbox. This app deals with cryptographic keys and therefore makes total sense trying to keep jailbroken devices from using it. Keys could get modified/corrupted and afterward uploaded to the database.

Those "criptographic keys" (they are called diagnostic keys) are already published on the notification server, and anyone can download them. The RPIs scaned by your phone are broadcasted by other phones over the air and can't be considered privated at all (you can capture them with an android phone or an ESP32).

The only sensitive information are the user own TEKs and is in the best interest of the user to keep them private, so a jailbroken user can't acess anything a normal user can't (except its own teks) so a jailbroken detection doesn't add any "value" like it would do for a banking app.

**Comment by pantic79** [comment]
Jailbreak detection removed. Check 2d1505d4858642995ea09f02f23c953acaa65195

Thanks.
