### ISSUE TITLE
Issue deleting diagnostic code

### ISSUE THREAD

**Issue by omartinma** [RadarCOVID/radar-covid-ios#23]
Hello,

I just found a small issue when typing the diagnostic code. If you fill the 12 chars and try to remove the last one then 2 chars will be removed instead of just one.

Thanks.

**Comment by jorgej-ramos** [comment]
There is a [PR](https://github.com/RadarCOVID/radar-covid-ios/pull/27) for this issue

**Comment by pantic79** [comment]
Thanks for detecting and fixing the issue. Unfortunately in this moment this fix is not applicable because some accesibility issues have been fixed in the last release and the component used to enter the code has been replaced by a text box.

Anyway, thanks a lot for your contribution!.
