### ISSUE TITLE
[URGENT] Version 1.0.6 targets PRE-production server

### ISSUE THREAD

**Issue by JuanpaG94** [RadarCOVID/radar-covid-ios#24]
The latest update uploaded to the App Store, which version is 1.0.6, is using the **pre-production backend**, which is not intended and will cause the app to not work for anybody who updates to this 1.0.6 version.

Pre-production **must not be** in an App Store update which is intended to be spread to all final users. This needs to target production server. 
This is an urgent issue that must be resolved quickly because the app will not work if everyone update to the latest version.

**To prevent more users to update to this in the next hours and prevent another "kind-of virus spread", you just can:**
1. Remove the app from sale, this will hide the app
2. Submit immediately a new update with the latest version or the new version targetting production server
3. Re-enable the app from sale on iTunes Connect

You need to make a new build targetting production servers as you have on this file: 
https://github.com/RadarCOVID/radar-covid-ios/blob/develop/RadarCovid/Config/Config.swift

![EiBoI96X0AAB3kp](https://user-images.githubusercontent.com/33027054/93321709-c9628c00-f812-11ea-8f7d-2aa39663f6e0.jpeg)

**Update**: They're aware of the issue. I've contacted them and they told me that they have fixed it server side and also pushed a new urgent update to AppStore.

**Comment by JuanpaG94** [comment]
cc/ @alopezh

**Comment by jorgej-ramos** [comment]
Since there's no way to rollback a version on AppStore, I suggest to remove RadarCOVID from AppStore and send a new update requesting an expedited review.

**Comment by JuanpaG94** [comment]
You're right @jorgej-ramos my bad, I updated the issue

**Comment by JuanpaG94** [comment]
**Update**: They're aware of the issue. I've contacted them and they told me that they have fixed it server side and also pushed a new urgent update to AppStore.

I'll close the issue when it's demonstrated

**Comment by alopezh** [comment]
A new version has been submited via expedited review

To prevent users that has already updated to 1.0.6 access the wrong environment, all request to: 

- https://radarcovidpre.covid19.gob.es

has been redirected to:

- https://radarcovid.covid19.gob.es

**Comment by pvieito** [comment]
@alopezh Great, thanks!

**Comment by aalmenar** [comment]
Can we take is as a new step to deploy new versions to TestFlight before placing them into production so people also collaborating here can help intercept issues like this for the good of all us and have more manpower to help?


> A new version has been submited via expedited review
> 
> To prevent users that has already updated to 1.0.6 access the wrong environment, all request to:
> 
> * https://radarcovidpre.covid19.gob.es
> 
> has been redirected to:
> 
> * https://radarcovid.covid19.gob.es

**Comment by pvieito** [comment]
@alopezh Maybe for the future would be a good idea to have a public TestFlight beta release of the app so the community could test it before the production release (as we cannot build it without the Exposure Notification entitlement).

**Comment by mtaberna** [comment]
I was not able to find any details in the latest iOS Github release, can we document production bug fixes properly, please?

**Comment by aalmenar** [comment]
Version 1.0.7 is out on the App Store

**Comment by JuanpaG94** [comment]
Closing this issue due to it's been addressed 👍

**Comment by avallesalas** [comment]
Version 1.07 is already available at the appStore.
Good job!!
