### ISSUE TITLE
Updating does NOT work (in Madrid)

### ISSUE THREAD

**Issue by ouboub** [RadarCOVID/radar-covid-ios#25]
Hi
I installed the app in 1. July, but went to germany, since a week I am back, but last update according to the app is 1.7.2020
(I attach the screenshots), 2 friends of mine have update, 1.9.2020 which is also bad the other has 15.9.2020 which seems better
I also looked up in (using iOs 13.7) 
Exposure Notifcation (new in 13.7)--> Exposure Logging Status-->Exposure Checks:

There I see sort of activity Matched Key Count 0
**BUT** no daily keys were downloaded
I germany I obtained every day up to 5000 keys (and no match)
Something is not right here.
Any advice is strongly appreciated
regards
Uwe Brauer
![0f1a128a-6b2c-4128-8de6-6730807386fc](https://user-images.githubusercontent.com/5957203/93353623-6ede2580-f83c-11ea-99e5-0ea32904c234.JPG)
![IMG_3294](https://user-images.githubusercontent.com/5957203/93353666-7998ba80-f83c-11ea-90d1-6e5967bf586e.PNG)
![29ba63db-5635-425d-81dc-94ad396dfd81](https://user-images.githubusercontent.com/5957203/93353704-82898c00-f83c-11ea-9580-44009e9df970.JPG)
[ExposureChecks-2020-09-16-json.txt](https://github.com/RadarCOVID/radar-covid-ios/files/5232884/ExposureChecks-2020-09-16-json.txt)

**Comment by aalmenar** [comment]
There’s a new update on the App Store that solves that issue, please update it.

**Comment by ouboub** [comment]
> There’s a new update on the App Store that solves that issue, please update it.

well it was not indicated in the App, as an update, I searched for it and indeed it says update, so I updated to 1.0.7
I will observe it and report back either tomorrow or on Friday.

**Comment by jorgej-ramos** [comment]
This issue should be close, as far as it's working now since version 1.0.7

**Comment by ouboub** [comment]
> This issue should be close, as far as it's working now since version 1.0.7

right, I confirm that it downloads the keys now, **however** I am curious to see, whether it does that in the background without opening the app, that was (and still is to some extend) a big issue with the german app. people interested in the app open it every day 2 or 3 times, so it took some time to realize that there was a problem with the app when you don't open it for some days. that is what I will do, if I see a problem, I will report back, 
Feel free to close the issue now

**Comment by jorgej-ramos** [comment]
[DP3T iOS SDK](https://github.com/DP-3T/dp3t-sdk-ios) takes care about background updates. 
As far as I know CoronaWarn does not use this dependency

**Comment by pantic79** [comment]
As commented before is already working on 1.0.7 version and @jorgej-ramos  is right, the German APP doesn't use DP3T.

Thanks.
