### ISSUE TITLE
Exposure notifications won't enable

### ISSUE THREAD

**Issue by desero86** [RadarCOVID/radar-covid-ios#29]
I'm facing the following bug:

Exposure notification switch in the app is off and disabled, I can't change its value.

![IMG_3228](https://user-images.githubusercontent.com/1073127/93686936-ebca0300-fab9-11ea-987f-5f892ad75d52.png)

If I check the app settings in iOS Settings App and open the Exposure Notifications permission, is empty:

![IMG_3226 copia](https://user-images.githubusercontent.com/1073127/93686865-7fe79a80-fab9-11ea-9d20-dbf30ae546e1.png)

![IMG_3227](https://user-images.githubusercontent.com/1073127/93686918-cb01ad80-fab9-11ea-8a30-d15562349ffc.png)

I think it's the same bug that [this](https://github.com/corona-warn-app/cwa-app-ios/issues/911) in the German app. I tried to install the configuration profile provided in the fix but it's seems is not longer valid, it can't be installed.

I have the last version of the app (1.0.7) running on iOS 14 but the problem surfaced first when on 13.7.

**Comment by CarlosJimenez** [comment]
I had a similar issue. Was fixed when I uninstall and install again the app. Just in case that helps
https://github.com/RadarCOVID/radar-covid-ios/issues/26

**Comment by pantic79** [comment]
@desero86, we were unable to reproduce the issue. Are you facing this problem yet?.

Thanks.

**Comment by desero86** [comment]
> @desero86, we were unable to reproduce the issue. Are you facing this problem yet?.
> 
> Thanks.

Sorry for the late answer, I had to reset the privacy and location settings in order to get it working again. Maybe it’s a bug at the OS level.
