### ISSUE TITLE
Application compatibility

### ISSUE THREAD

**Issue by darkRyuutarou** [RadarCOVID/radar-covid-ios#34]
En estos momentos en el que la lucha contra el COVID-19 es esencial en nuestro país no tiene sentido que se haya diseñado a nivel técnico y funcional la aplicación con una restricción tan básica como obligar a los usuarios a disponer de, al menos, la versión 13.5 de iOS para poder hacer un uso de una aplicación en estos tiempos tan esencial como es esta.

Sé que el motivo técnico que se argumenta de forzar la compatibilidad a iOS 13.5 como mínimo es usar la API de Apple para la notificaciones de detección.

Si Apple, por algún motivo que no ha hecho público, desea forzar la obsolescencia programada de los dispositivos con excusa de su API para notificaciones de exposición y detección, esto no es motivo que de cara a un diseño funcional de la aplicación se fuerce a los usuarios a actualizar los dispositivos Hardware en estos momentos, con el impacto económico que ello conlleva. Recordemos que en estos momentos la gran cantidad de población que se encuentra en paro o ERTES en España con motivo del COVID-19.

Además, hemos de recordar que la prensa ya se ha hecho eco de las limitaciones de la aplicación dejando un gran volumen de dispositivos fuera del alcance y uso de la misma, limitando de gran manera la efectividad que puede tener la aplicación ya que, para que pueda tener los resultados que se esperan de ella, es necesario que se la instalen una amplia mayoría de los usuarios.

Por todo lo expuesto, solicito un replanteamiento de los requisitos funcionales de la aplicación para que, se tenga en cuenta dispositivos que no están soportados  y de manera paralela se trabaje con otro protocolo que al menos permita a esos usuarios poder acceder a las notificaciones, tal y como se ha realizado en otras aplicaciones similares de otros países como la del NHS del Reino Unido, COVIDSafe de Australia, o en otros modelos de éxito en el uso y despliegue de este tipo de aplicaciones como es el de Corea del Sur o China.

Referencias:
https://www.elespanol.com/omicrono/software/20200819/no-funciona-movil-rastreo-radar-covid-gobierno/513949006_0.html
https://www.abc.es/tecnologia/moviles/aplicaciones/abci-no-puedes-descargar-radar-covid-gobierno-deja-33-millones-espanoles-sin-poder-usar-aplicacion-202009141944_noticia.html
https://www.diariodesevilla.es/tecnologia/app-rastreo-RADAR-Covid-no-funciona-moviles_0_1493550811.html
https://www.applesfera.com/ios/ios-12-4-9-deseable-version-que-esperamos-soporte-a-api-radar-covid-para-iphone-5s-iphone-6
https://elpais.com/tecnologia/2020-08-13/por-que-no-puede-descargarse-radar-covid-en-algunos-moviles-chinos-y-otras-dudas-tecnicas-sobre-la-app.html
https://support.apple.com/es-es/guide/iphone/iphe3fa5df43/13.0/ios/13.0

**Comment by jorgej-ramos** [comment]
Dejando de lado el hecho de que los requisitos para hacer funcionar el API Apple-Google no vienen impuestos por el equipo de RadarCOVID, podríamos intentar analizar el porcentaje total mundial (no solo a nivel español) de terminales cubiertos con esta solución. 

En [este hilo de twitter](https://twitter.com/i/events/1301410427977564160) trato de explicarlo lo mejor que puedo. No obstante, el resumen es: más del 90% de los terminales de todo el mundo cubiertos.
En el caso de iOS, los terminales compatibles están a partir del iPhone 6S, que salió a la venta el 25 de Septiembre de 2015.
En el caso de Android, los terminales compatibles están a partir de Android 6, que salió el 5 de Octubre de 2015.

No olvidemos también que este esfuerzo principal proviene del equipo europeo DP3T, y fueron Apple y Google los que a posteriori se acercaron al proyecto para colaborar con su implantación en los terminales de sus marcas. A los gobiernos y a los usuarios, esto nos ha caído "de gratis", casi podríamos decir.
Por lo tanto yo descartaría intereses oscuros o conspiranoicos en lo que a los requisitos se refiere.

Por otro lado, otros sistemas de rastreo de contactos no aseguran de forma fehaciente ni la seguridad ni la privacidad del sistema. Por ejemplo, el citado modelo de Australia se basa en el de Singapur, cuya base es [BlueTrace](https://bluetrace.io) y fue desarrollada por el propio gobierno de Singapur (ver también la referencia a [PEPP-PT](https://en.wikipedia.org/wiki/Pan-European_Privacy-Preserving_Proximity_Tracing).)

Reino Unido se ha dado cuenta de esto y ha preferido [echar para atrás](https://www.bbc.co.uk/news/technology-53095336) y utilizar DP3T.

La principal diferencia entre los sistemas PEPP-PT y DP3T es, por tanto, la descentralización del procesamiento de informes de contagio. Levantando la vista un poco podemos comprobar como en Europa, la adopción de DP3T como protocolo de rastreo de contactos es una constante y, viendo el caso de Reino Unido, ir contracorriente es prácticamente un fracaso seguro.

En lo particular opino que DP3T es, de lejos, el equilibro perfecto entre privacidad y rastreo eficiente de contactos.

Como en todos los sistemas, siempre hay margen de mejora. Pero creo que la adopción de sistemas NO-DP3T supondrían un paso atrás muy grande a nivel local, estatal y europeo.
No olvidar también que las aplicaciones de rastreo son solo una capa mas de seguridad, no la solución definitiva.

**Comment by darkRyuutarou** [comment]
Buenos días,

Ante todo gracias por la respuesta @jorgej-ramos. 
Por otro lado creo que con algo tan serio hacer downvotes por parte de algunos usuarios, denota que no se toma esto con la suficiente seriedad por los mismos.

He analizado con detenimiento tu respuesta. Creo que es mejor ir por partes.

Comentas en primer lugar sobre la penetración de los terminales. Das un dato de una penetración aproximada de un 90% de iOS 13 a nivel global, pero la explicación es para España y enfocada a los usuarios españoles, por lo que enfocarnos en una estadística global no quiere decir que la situación del mercado español sea idéntica a nivel de penetración. Afirmar datos de esta manera no deja de ser una manera de autoengañarnos, porque la extrapolación de datos global a nivel de país se basa siempre en una suposición del comportamiento de consumo de los habitantes de país.

Comentas también el caso de Android. Actualmente en España Android tiene una penetración a Junio 2020 del 89,3% de los dispositivos móviles smartphone, mientras que los dispotivos iOS de 10,7% (https://www.statista.com/statistics/260419/market-share-held-by-smartphone-operating-systems-in-spain/).
Según el diario Expansión en el año 2018 se estimaba que el 80% de la población española disponía de un smartphone (https://www.expansion.com/economia-digital/innovacion/2018/02/01/5a72e73a22601db2288b4658.html) lo que se traducía en unos 37,27 millones de usuarios de dispositivos smartphone en 2018. 
Adicionalmente tenemos que sumar la extrema fragmentación de versiones de software de dispositivos Android, muy superior a la de dispositivos iOS y que por ejemplo, hoy en día un gran número de dispositivos smartphone Android de bajo coste, destinados a un público que bien no quiera invertir en tu terminal de muchas prestaciones o no tenga mucha capacidad adquisitiva hoy en día se siguen publicando con versiones anteriores a Android 6, siendo un gran volumen de ventas de smartphone en nuestro país este segmento. Adicionalmente, tenemos que tener en cuenta que todos los usuarios de Huawei y Honor tampoco tienen acceso a la aplicación Radar Covid en Android (teniendo en cuenta que el volumen de usuarios de Huawei supone casi prácticamente el mismo que de usuarios iOS en España a fecha Septiembre 2020 al ser un 18,2% del total, https://gs.statcounter.com/vendor-market-share/mobile/spain). 
Partiendo de todos estos datos implicaría que hablamos de unos 3,98 millones de dispositivos iOS y de 33,28 millones de dispositivos Android. Si cogemos así mismo el dato de penetración de iOS 13 o superior que has indicado (recordemos que no tenemos tampoco datos oficiales por la propia Apple) nos dice que 398 mil personas en España no se podrían instalar en iOS la aplicación, y posteriormente en Android los usuarios de Huawei que potencialmente pueden estar impactados al no poder instalar la aplicación es de 6,7 millones, sin tener en cuenta los usuarios que, además tengan versiones de dispositivos anteriores a Android 6.
En total, haciendo un cálculo rápido con los datos expuestos nos dicen que aproximadamente unos 7.1 millones de usuarios en España no pueden instalarse potencialmente la aplicación, dato que al no tener nadie la foto exacta de los usuarios smartphone, dispositivos y versiones que usan es simplemente una aproximación y puede variar tanto por encima como por debajo.
Estos 7,1 millones para que nos hagamos una idea del volumen real que puede implicar es como si tomáramos a todos estos habitantes y por ejemplo dijéramos que todos los habitantes de la Comunidad de Madrid no se pueden instalar la aplicación por no tener dispositivos compatibles (https://es.wikipedia.org/wiki/Anexo:Provincias_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a) o que la suma de los habitantes de Barcelona y Acoruña tampoco podrían, y así podríamos hacer muchas similitudes.

En el día de hoy ha salido en la prensa de que en España apenas llega al 10% de los habitantes los que se han instalado radar COVID: https://www.eldiario.es/tecnologia/descargas-logrando-apps-rastreo-covid-europa_1_6303188.html
Probablemente las cifras de implantación no serían las que son sin tener las limitaciones.

Me comentas de manera negativa otras aplicaciones, pero es que incluso, aunque sean peores tienen niveles de implantación muy superiores a la de España. En el caso de la del NHS de UK su implantación es superior al 20%, es decir, el doble aunque no sean números para tirar cohetes.

Continuando la argumentación, me remites a un hilo de tu twitter personal (https://twitter.com/i/events/1301410427977564160) pero sinceramente: estamos en el repositorio del RadarCOVID, dar explicaciones sitios personales no explica el motivo por el que se han tomado de esa manera las decisiones, y se debería de apuntar en cualquier caso a la documentación oficial que recordemos que de manera procedimental en la Administración Pública en el momento de la entrega de un proyecto para poder proceder al cobro de la factura por el proyecto tecnológico desempeñado se debe de presentar toda la documentación necesaria.

A los usuarios en ningún caso nos ha caido de gratis. La aplicación RadarCOVID ha costado a todos los contribuyentes 273171,5€ más IVA, quedándose en un total de 330537,52€. Esta contratación de manera directa y por procedimiento de Urgencia en el pasado mes de Junio se realizó a Indra tal y como podemos ver en la web de Contratación del Estado incluyendo dichos importes: https://beta.documentcloud.org/documents/20383564-doc_can_adj2020-157779
Acuerdo de contratación de urgencia: https://contrataciondelestado.es/wps/wcm/connect/02e79307-5c3c-405c-9beb-067561208e0a/DOC20200615123547report+3852+-+Acuerdo+tramitacion+EMERGENCIA+SGAD.pdf?MOD=AJPERES
Detalle completo de la Licitación: https://contrataciondelestado.es/wps/portal/!ut/p/b0/04_Sj9CPykssy0xPLMnMz0vMAfIjU1JTC3Iy87KtUlJLEnNyUuNzMpMzSxKTgQr0w_Wj9KMyU1zLcvQjzQK8TJOMgkxTfb2LqozdA1NMi8yCA21t9Qtycx0BiFPTzw!!/

Una vez explicado esto, dado que "gratis" la aplicación no ha sido y ha habido una empresa beneficiada, Indra.

Como me imagino que o bien trabajas para Indra o bien eres un técnico de la Secretaría de Estado que sacó la licitación (disculpa si no eres ninguno de los dos casos, pero hago esta suposición en base a las afirmaciones que realizas), bien sabrás que el desarrollo de software así como los proyectos de desarrollo y mantenimiento de los mismos se hacen siempre basándose en el principio de universalidad, obligando a soportar o bien dispositivos o software muy obsoletos a nivel tecnológico, te pongo ejemplo: mínimo Internet Explorer 6 o 7 en el caso de webs, a nivel de servidores te sorprenderías la cantidad de aplicaciones del estado que a día de hoy siguen funcionando y se siguen manteniendo en Java 5 o Java 6, y así podría seguir siguiendo con muchos ejemplos.

Dado que entiendo que el Estado en este sentido no se habrá saltado este precepto de universalidad de acceso al nuevo recurso que siempre ha venido realizando en todos los años anteriores y dado que tampoco se trata de una solución llave en mano como puede ser una solución hecha a medida para una necesidad interna de cualquier Organismo del Estado no se está cumpliendo en este caso.

Dado que comentas que usar otro protocolo o incluso uno propietario sería un retroceso, incluso no se plantea la posibilidad de que se usen varios protocolos dependiendo del SO del terminal, rogaría que compartieras con todos el documento funcional y técnico por el que se planteó la aplicación.

La aplicación en estos momentos se encuentra en periodo de garantía en el plazo de adjudicación prevista hasta el 15 de Noviembre, por lo que en el caso de defectos tan graves como los planteados todavía se está a tiempo para que se corrijan.

Es verdad que las aplicaciones de rastreo no son las únicas armas de lucha contra la COVID-19, pero teniendo en cuenta que las graves deficiencias que está demostrando España tanto en número de rastreadores como en pruebas PCR comparado con países que han llevado esta crisis con éxito como en Corea del Sur o Nueva Zelanda, escoger el camino de limitar a los usuarios con una aplicación desarrollada con dinero público no es el mejor de los objetivos.

Por todo lo expuesto solicito que se :
- Documento del análisis funcional y técnico. Sería conveniente compartir estos análisis aquí en la documentación del GitHub.
- Replanteamiento del alcance funcional a fin de que alcance los dispotivos que actualmente no están soportados.

Debemos de tener en cuenta que a los usuarios debemos de dar todas las herramientas posibles, de esta forma podemos llegar potencialmente a más usuarios que puedan tener la aplicación instalada. Hemos de recordar que la limitación de de dispositivos en los que se puede instalar ha sido la gran queja tanto de usuarios de dispositivos smartphone como de medios de comunicación.

**Comment by jorgej-ramos** [comment]
> Comentas en primer lugar sobre la penetración de los terminales [...] pero la explicación es para España y enfocada a los usuarios españoles

La pandemia no afecta solo a España, y España se encuadra dentro del marco Europeo. Política y geográficamente. Tratar de desmarcarse con una solución ombliguista es perder la partida. Creo que entender el problema pasa por aceptar que la solución es conjunta o no será.

---

> y posteriormente en Android los usuarios de Huawei que potencialmente pueden estar impactados al no poder instalar la aplicación

En el caso de Google, dado que ha sido una de las empresas que ha implementado el protocolo DP3T, su sistema esta preparado para ello mediante sus servicios Google Services. 
Huawei es una marca independiente, que no ha realizado ningún esfuerzo a nivel de su sistema para facilitar esta labor. No entro en razones, esta es la realidad: algunos terminales Huawei (y otras marcas chinas) no implementan Google Services y por tanto no son compatibles.
Creo que achacar este problema a la empresa que mantiene esta aplicación o a cualquier otro actor de este sistema es, sencillamente, no conocer cómo funciona.

---

> Me comentas de manera negativa otras aplicaciones, pero es que incluso, aunque sean peores tienen niveles de implantación muy superiores a la de España.

En esto entran otro tipo de disciplinas que considero que no es el lugar de comentarlas, dado que exceden lo puramente técnico. Como está ocurriendo con este hilo, al que contesto ya por alusiones.

---

> pero sinceramente: estamos en el repositorio del RadarCOVID, dar explicaciones sitios personales no explica el motivo por el que se han tomado de esa manera las decisiones

Trataba de aportar luz con datos extraídos de fuentes oficiales. No obstante es cierto, estamos en un repositorio de código, concretamente en el de RadarCOVID. Quizá este tipo de discusiones tampoco sean las adecuadas para el lugar.

---

> Probablemente las cifras de implantación no serían las que son sin tener las limitaciones.

Tengo serias dudas. Creo que la respuesta está en el nivel de competencias digitales de la población, así como en la educación y concienciación por parte de gobierno e instituciones. La limitación por requisitos técnicos no es la razón principal.

---

> A los usuarios en ningún caso nos ha caido de gratis

Rotundamente si. No diferenciar RadarCOVID de su protocolo DP3T es la principal causa de estos errores de conceptualización. RadarCOVID es la implementación de un protocolo internacional y de libre acceso, en el que han trabajado decenas de personas. Dicho protocolo está por encima de cualquier tipo de decision empresarial o gubernamental, como [su propia documentación oficial](https://github.com/DP-3T/documents) explica.

Pero insistir una vez mas en que RadarCOVID está aquí, en parte, por el esfuerzo del propio equipo DP3T y el de compañías como Apple y Google que, **sin coste**, han creado y facilitado la implementación. 
La capa que se ha desarrollado en España es la última y, además del desarrollo de la app, entiendo que incluye el desarrollo de los servidores y mantenimiento operacional. Como es lógico, ésta última capa tiene un coste. Creo que aquí estamos de acuerdo todos.

---

> Como me imagino que o bien trabajas para Indra o bien eres un técnico de la Secretaría de Estado

Ninguna de las dos. Soy un trabajador por cuenta ajena, como cualquier otro. No tengo ninguna relación con RadarCOVID ni con terceros.

---

> bien sabrás que el desarrollo de software así como los proyectos de desarrollo y mantenimiento de los mismos se hacen siempre basándose en el principio de universalidad

Lo siento pero esto no es así. Todos los proyectos tienen requisitos mínimos. Incluso los públicos. La tecnología avanza y en ciertas ocasiones el coste de mantener dispositivos obsoletos es mayor que el coste del propio proyecto. No es el caso de RadarCOVID, en el que las razones son otras, ya muy comentadas y discutidas.

---

> Dado que comentas que usar otro protocolo o incluso uno propietario sería un retroceso, incluso no se plantea la posibilidad de que se usen varios protocolos dependiendo del SO del terminal, rogaría que compartieras con todos el documento funcional y técnico por el que se planteó la aplicación.

No entiendo las suspicacias. Creo que es bastante obvio que la apuesta europea por DP3T está mas que documentada y avalada. No obstante este es un foro técnico y no legal.

---

> escoger el camino de limitar a los usuarios con una aplicación desarrollada con dinero público no es el mejor de los objetivos.

Una vez mas: no es competencia ni de la empresa que mantiene RadarCOVID ni del Gobierno Español establecer limitaciones en cuanto a requisitos mínimos. Sencillamente no pueden hacer nada al respecto. Existe un porqué técnico en cuanto a BLE, sistemas de permisos y otros limitantes de hardware.

Esta discusión me recuerda a la típica historia de las comunidades de vecinos, el ascensor y el vecino del bajo. Casualmente yo vivo en un bajo. No uso el ascensor y lo pago, al igual que todos los demás vecinos. Pero, una vez más, no se trata sólo de mi y de mi casa. Se trata de que el vecino del 13 no puede subir andando porque es cojo.
Supongo que se entiende el paralelismo.
 
---

En resumen:
Mientras no consigamos entender que este problema no es solo de España no avanzaremos. Es un problema global y, como tal, la respuesta ha de ser lo mas global posible. Un sistema de rastreo a nivel europeo creo que es lo mejor que nos podría pasar.

Las limitaciones técnicas son las que son y tanto la prensa, como muchos de los usuarios, no tienen los conocimientos técnicos suficientes como para entender el porqué de los requisitos mínimos necesarios. De ahí que en mi hilo de twitter trate de explicarlo de una manera sencilla. Aunque hay veces que ni con esas.

Quizá la prensa no sea el mejor sitio para consultar opiniones técnicas adecuadas, supongo. Este mensaje tampoco pretende serlo, por cierto.

Pretender implantar sistemas diferentes, basándose en cifras de éxito de países con sistemas políticos y sociales totalmente opuestos, creo que es analizar el problema partiendo desde un punto de vista equivocado.

¿Mejorar? por supuesto: por ejemplo, un sistema de registro manual de códigos QR por establecimiento visitado, cubriría un montón más de casos de infección y podría implementarse también en RadarCOVID. Incluso este sistema de escaneo de QR sería válido para sistemas anteriores a iOS 13 o Android 6 y ambos podrían convivir dentro de la misma app. Pero esto tiene un precio ya no solo de desarrollo, sino de gestión, imprenta y normalización del sistema ¿estaríamos dispuestos a asumirlo?

O también se puede ayudar contribuyendo con ideas y código a este repositorio como hemos hecho muchos.

Personalmente me alegro de que DP3T sea una decisión inamovible:
- Prácticamente toda Europa avala el uso de este protocolo
- Es respetuosa con la privacidad de las personas, por diseño. Decir lo contrario es no haberse leído su documentación
- Multinacionales de reconocido nombre aportan sus sistemas para facilitar la implementación
- Se pueden crear corredores seguros a través de esta tecnología entre los países que la implementan

Las posibilidades son muchas y las facilidades para crear aplicaciones de rastreo son prácticamente todas gracias al equipo DP3T primero, y a Apple y Google después por preparar sus sistemas para alojar este protocolo.

Sinceramente creo que esta conversación no da para mucho mas. Espero haber podido aportar algo de luz.

**Comment by pantic79** [comment]
Hola,

todas las opiniones son respetables, pero creo que este no es el foro en el que tratar muchos de estos temas. Principalmente porque desde el ámbito técnico no podemos dar respuesta a gran parte de los comentarios realizados, ya que corresponden a otro ámbito. Creo que las puntualizaciones/comentarios técnicos realizados por @jorgej-ramos son muy acertados y, en este sentido, poco más podemos aportar desde el equipo de desarrollo.

Respecto a aquellos aspectos que sí pudieran estar más relacionados con el aspecto técnico, os animo a abrir las issues correspondientes. Por ejemplo, habéis comentado temas de documentación del proyecto, y esto es algo en lo que ya estamos trabajando y que iremos liberando en próximas fechas de acuerdo a las prioridades establecidas.

Solo comentar que todo el equipo de Radar COVID, compuesto por varios profesionales, vinculados y no vinculados a la consultora mencionada, ha volcado su ilusión y sus esfuerzos en el desarrollo de esta aplicación no sólo por una vinculación contractual, sino pensando en hacer algo que contribuyera a luchar contra la pandemia, desde el convencimiento de que se trata de una herramienta útil y necesaria para este fin.  Os agradecemos toda vuestra ayuda para ir mejorando la aplicación y que cada vez más personas entiendan su funcionamiento, se la instalen y de esta forma nos ayudemos tod@s a frenar la expansión del virus.

Gracias!
