### ISSUE TITLE
Sharing the diagnosis with other EU apps should be the default option

### ISSUE THREAD

**Issue by pvieito** [RadarCOVID/radar-covid-ios#39]
Sharing the diagnosis with other EU apps should be the default option. 

It seems that currently the default option is to only share it with Radar COVID users: 

![C23D326E-CB0F-405C-BACE-7181F475A39E](https://user-images.githubusercontent.com/1706695/97806219-d7e9f300-1c5a-11eb-8763-455226381ac1.jpeg)

I don’t understand this design choice, IMHO it seems like a dark design pattern. I would even argue that there should not be a choice at all to restrict the diagnosis to only Radar COVID users (a simple notice should be sufficient), but if it has to be there, it should not be the default one for multiple reasons:

- Some users will not read or understand the choice. 
- Some users will think that if there is a choice and it is not the default there should be something _bad_ about it.
- Some users may think they only have to select the EU apps option if they have traveled to other countries. This is not true, it is important to alert users of EU apps visiting Spain.
- Deference to other EU apps which have been sharing all their diagnoses with the EFGS.

Also, as there is [no longer a way to retrieve TEKs shared from Radar COVID without being merged with other EFGS TEKs](https://github.com/RadarCOVID/radar-covid-backend-dp3t-server/issues/7) nor public statistics, the community cannot measure how problematic this design decision is (ie. the fraction of users which have not opted in sharing the diagnosis with EU apps).

**NOTE**: I have only tested this behavior with the iOS app but I suppose it also applies to the Android app as well.

**Comment by jorgej-ramos** [comment]
UX patterns can be confusing, as @pvieito exposes. Moreover, I believe that keeping the system consistent is important: if we cannot really differentiate the TEKs when downloading them, there should be no differences when uploading them.

IMHO doing this decompenses the upload/download requests without any apparent business rule.

**Comment by viCasco** [comment]
Also confirmed in the Andorid app.
![image](https://user-images.githubusercontent.com/12234619/97811172-20b0a480-1c79-11eb-8301-99f06d40c9b7.png)

**Comment by pvieito** [comment]
Also, if the option to choose is not removed they should be relabeled more clearly: 

– Warn Radar COVID and other EU apps users (Alertar a usuarios de Radar COVID y otras aplicaciones europeas) [default]
– Only warn Radar COVID users (Solo alertar a usuarios de Radar COVID)

**Comment by pantic79** [comment]
Hello,

this behaviour will be changed in the next release in order to share keys with Europe by default.

Thanks for your contribution.

**Comment by jorgej-ramos** [comment]
Great news! Thank you for the updates @pantic79

**Comment by pvieito** [comment]
@pantic79 Great to hear that, thanks!
