### ISSUE TITLE
[URGENT] Radar COVID App Store version is not updated with DP3T SDK 1.2.1

### ISSUE THREAD

**Issue by pvieito** [RadarCOVID/radar-covid-ios#4]
🔑 The [DP3T SDK version 1.2.1](https://github.com/DP-3T/dp3t-sdk-ios/releases/tag/1.2.1) solved a bug to make exposure detections work again on iOS 13.7 and iOS 14.

The App Store version of Radar COVID should be updated ASAP.

**Comment by jorgej-ramos** [comment]
Does anybody read this issues? RadarCOVID v1.0.5 is 3 weeks old now and DP3T SDK v1.2.1 was released 11 days ago.

Since iOS 13.7 lets you opt-in to the COVID-19 Exposure Notifications system without the need to download an app (as documented on [Apple Release Notes](https://support.apple.com/en-us/HT210393#137)) we should assume a higher penetration rate than other iOS13 updates.

**Comment by pvieito** [comment]
@jorgej-ramos Note that Exposure Notification Express (ie. app-less Exposure Notification) requires an integration between a Public Health Authority and Apple/Google. This is only available on some United States regions. Other regions, Spain included, continue to require an app for Exposure Notifications.

But in iOS 13.7 Apple has indeed added a boarding screen to make easier the download of Notification Exposure apps of each region so it is correct to assume a bigger penetration.

In any case the update should have been released before iOS 13.7 being public.

**Comment by pvieito** [comment]
Twitter thread about the problem: https://twitter.com/pvieito/status/1304172744536399873?s=21

**Comment by jorgej-ramos** [comment]
Of course, I'm aware. Perhaps my expression was not the best: I wanted to state that since the 13.7 update offers that possibility, RadarCOVID should have been updated the same day as the iOS 13.7 release. 11 days since the fix was published in the DP3T SDK should be more than enough to have already updated.

Thank you for your work!

**Comment by pvieito** [comment]
@jorgej-ramos Exactly!

**Comment by jorgej-ramos** [comment]
I'm actually just ranting. It seems incredible to me that in two days there is no answer to this important problem.

I refer to this issue in this twitter thread:
https://twitter.com/YoryoBass/status/1304309087560228864?s=20

**Comment by pvieito** [comment]
I’ve just asked Carme Artigas (the political leader of the project) if she has any insight on the update release date: https://twitter.com/pvieito/status/1304714609799069696?s=21

**Comment by aalmenar** [comment]
@pvieito i just did the same yesterday https://twitter.com/aalmenar/status/1304452362824749056

**Comment by pvieito** [comment]
@aalmenar Great, thanks!

It’s a bit discouraging the silence of the project maintainers about this issue 3 days later 😔

**Comment by JuanpaG94** [comment]
The team should update the app as soon as possible because it's not working due to that issue. 
Dev team: this is extremely **URGENT**, the app will not work on iOS 13.7 and iOS 14(it's release is planned for this month) till this is fixed.

**Comment by jorgej-ramos** [comment]
14 days now since the release of [DP3T SDK version 1.2.1](https://github.com/DP-3T/dp3t-sdk-ios/releases/tag/1.2.1), and consequently the solution to this problem. 14 days.
🤦

**Comment by pvieito** [comment]
So here we are, iOS 14 is being released tomorrow and there is neither an update released nor any answer from the project maintainers: https://www.theverge.com/2020/9/15/21436979/apple-ios-ipados-14-release-date-september-16?utm_campaign=theverge&utm_content=chorus&utm_medium=social&utm_source=twitter

**Comment by jorgej-ramos** [comment]
I can't believe this.

**Comment by pvieito** [comment]
At least if they had started the integration with the European gateway (https://ec.europa.eu/commission/presscorner/detail/en/ip_20_1606) we could use the German or Italian app for exposure notifications but even that is not possible…

**Comment by jorgej-ramos** [comment]
This is a very frustrating situation. I can't understand how this can happen now, when technology can lend a hand.

**Comment by pvieito** [comment]
Fixed on Radar COVID 1.0.6! 🎉

**Comment by JuanpaG94** [comment]
Due to it's fixed now, you should close this issue

**Comment by pvieito** [comment]
No, now it is worse: https://twitter.com/yoryobass/status/1306158399118364673?s=21

Radar COVID 1.0.6 is now connecting to `https://radarcovidpre.covid19.gob.es` instead of `https://radarcovid.covid19.gob.es`.

We are getting test TEKs instead of real TEKs, and now all iOS versions are affected… 😓

**Comment by aalmenar** [comment]
Can confirm that. My DNS server is detecting requests only for radarcovidpre.covid19.gob.es @alopezh

**Comment by JuanpaG94** [comment]
This is unbelievable.

**Comment by jorgej-ramos** [comment]
I can also confirm, RadarCOVID is connecting against preproduction server
![IMG_1746](https://user-images.githubusercontent.com/1220565/93319110-c914c180-f80f-11ea-906e-96f48713f301.jpg)

**Comment by pvieito** [comment]
Hope they can fix this server-side…

**Comment by JuanpaG94** [comment]
They can't. They need to make a new build, with the correct environment (production) and request again another update into the App Store.

The fast solution is to rollback the new update to prevent more users to update to an useless build.

**Comment by jorgej-ramos** [comment]
> They can't. They need to make a new build, with the correct environment (production) and request again another update into the App Store.
> 
> The fast solution is to rollback the new update to prevent more users to update to an useless build.

Exactly. Urls are hardcoded on this file

https://github.com/RadarCOVID/radar-covid-ios/blob/develop/RadarCovid/Config/Config.swift

**Comment by pvieito** [comment]
Closing this issue, as it is kind of _solved_.

For more info about the Radar COVID 1.0.6 problem, check [this issue](https://github.com/RadarCOVID/radar-covid-ios/issues/24).
