### ISSUE TITLE
How many people have downloaded the app (including the android version)

### ISSUE THREAD

**Issue by ouboub** [RadarCOVID/radar-covid-ios#43]
Hi
According to 
https://as.com/meristation/2020/10/09/betech/1602269850_371869.html
only 10 % of the population has downloaded the app. That was in October, how is the situation now, and
where can I get actual information?
thanks and regards

Uwe Brauer

**Comment by pantic79** [comment]
Hello @ouboub,

yout could check this info in the stats view of the recently 1.2.0 app version released to stores, curently available in Play Store and in App Store soon.

Thanks:

**Comment by ouboub** [comment]
Thanks, it is still not availabe in the Apple Store, the 
play store https://play.google.com/store/apps/details?id=es.gob.radarcovid&hl=en&gl=US
tells me > 1 million. 
Gosh so few did download it? 
Android is more extended than Apple in Spain, so things look grim, I'd say.

**Comment by pantic79** [comment]
Sorry, I was meaning in the new stats functionality added in the 1.2.0 version. As I said, iOS version is being reviewed and will come soon.

Thanks.

**Comment by pvieito** [comment]
@pantic79 Hi, great update! Two related questions:
 - When is the updated source code going to be published?
 - How frequently are the in-app statistics going to be updated?

**Comment by pantic79** [comment]
Hello,

* Source code will be published on next Monday. We made some performance improvements to the DP3T original code and was not possible to publish on Friday.
* The intention is to refresh the stats every natural week but the refresh date depends on the delay imposed by the several data sources involved (in the next coming dashboard there are several ratio KPIs with data from different origins and must be time-synced in order to depict meaningful indicators). 

Thanks.

**Comment by ouboub** [comment]
>>> "p" == pantic79  <notifications@github.com> writes:

> Hello,
I just downloaded version 1.2.0

The statistic claim 5.653.519 downloads, but is this only of iOS or does
it include Android as well. 


> * Source code will be published on next Monday. We made some
> performance improvements to the DP3T original code and was not
> possible to publish on Friday. 

I am not sure what you mean by this. Are you saying that you push the
code, which version 1.2 is based on **only**  on Monday to the
repository.
So you release the source code after pushing the executables? That 
looks a bit odd I'd say


> * The intention is to refresh the stats every natural week but the
> refresh date depends on the delay imposed by the several data sources
> involved (in the next coming dashboard there are several ratio KPIs
> with data from different origins and must be time-synced in order to
> depict meaningful indicators).

Thank you

**Comment by pantic79** [comment]
Hello,

iOS + Android.

Thanks for your feedback, it will be taken into account to improve the source code pushing cadence. 

Thanks for your contribution and commitment.

**Comment by ouboub** [comment]
>>> "p" == pantic79  <notifications@github.com> writes:

> Hello,
> iOS + Android.

Thanks


> Thanks for your feedback, it will be taken into account to improve the source code pushing cadence. 

Sorry but I still don't understand, you push the source code after a
release?

How am I supposed to make a pull request?

**Comment by pantic79** [comment]
Hello,

you are free to submit your contributions as PRs to the develop branch. Definitively the idea is to push the changes regularly (once a week at least) but this time was not possible. Sorry for that.

Thanks.

**Comment by ouboub** [comment]
>>> "p" == pantic79  <notifications@github.com> writes:

> Hello,
> you are free to submit your contributions as PRs to the develop
> branch. Definitively the idea is to push the changes regularly (once a
> week at least) but this time was not possible. Sorry for that.

I just pulled, and look what I see
Removing RadarCovid/Application/JailBreakDetect.swift
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.

Two questions:

    1. Does RadarCovid run on Jailbroken devices.

    2. Shall I open a new issue for that merge problem?


I did not touch the code nor did I commit locally

regards

**Comment by pantic79** [comment]
Hello,

actually, I don't know what version you are trying to modify because in latest version in develop branch there is no such file (I mean JailBreakDetect.swift). Please, update your local develop branch from origin and open an issue in case problem is not already solved.

Answering to your question, Radar COVID runs on jailbroken devices (see b17d5bce9)

Thanks.

**Comment by ouboub** [comment]
> Hello,
> 
> actually, I don't know what version you are trying to modify because in latest version in develop branch there is no such file (I mean JailBreakDetect.swift). Please, update your local develop branch from origin and open an issue in case problem is not already solved.

All I am saying is, I cloned in November, now I pulled again and see this error, which is odd. So
I might be forced to clone **again**, like iin the screenshot attached

Hm the new clone is bigger 55MB versus 32 MB of the pull yesterday
![git](https://user-images.githubusercontent.com/5957203/102751268-b60e1200-4367-11eb-94f3-31f9bb17deb8.png)



> 
> Answering to your question, Radar COVID runs on jailbroken devices (see [b17d5bc](https://github.com/RadarCOVID/radar-covid-ios/commit/b17d5bce9176e3ed58942515e003338fa180846d))
> 
good to know thanks


> Thanks.

**Comment by pantic79** [comment]
Hello,

the behaviour you describe is quite strange so please open an issue to be tracked.

Thanks.

**Comment by ouboub** [comment]
>>> "p" == pantic79  <notifications@github.com> writes:

> Hello,
> the behaviour you describe is quite strange so please open an issue to be tracked.

Ok especially since git fsck returned an error

**Comment by iCesofT** [comment]
Hi,

there is already a window on app where you can see statistics. Also you can find more statistics in thise page:
https://radarcovid.gob.es/estadisticas/descargas-radar

Kind regards
