### ISSUE TITLE
Which version of ENF is Radar using?

### ISSUE THREAD

**Issue by fsbaraglia** [RadarCOVID/radar-covid-ios#47]
Hola, 

I have this statement inside my iPhone :
![image](https://user-images.githubusercontent.com/23255586/103756876-41e29800-5010-11eb-87d6-7b1c009fc45d.png)

I see as well this in the exposure.json:
```
{
      "Timestamp" : "2021-01-06 00:29:09 +0100",
      "Files" : [
        {
          "Hash" : "-----xxxxxFBB43",
          "KeyCount" : 355502,
          "AppBundleIdentifier" : "es.gob.radarcovid",
          "Timestamp" : "2021-01-06 00:29:12 +0100"
        }
      ],
      "AppBundleIdentifier" : "es.gob.radarcovid"
    }
```

but I don't see any risk of exposure in the Radar App.  
I am curious to know which version of the Exposure Notification Framework / the Exposure Notification System RADAR is using?

Version 1 or 2?

**Comment by pantic79** [comment]
Hello @fsbaraglia,

currently we are using version 2. Please, consider that a key match could imply a risky situation or not based on the attenuation and exposition duration.

Thanks.

**Comment by fsbaraglia** [comment]
Hi @pantic79 ,

nice, thank you very much for the info.
Interesting. in practice, the attenuation and exposition duration has not qualified the Match, right?
Do you have some official Apple documentation about this?

Thanks

**Comment by pantic79** [comment]
Hi @fsbaraglia,

that's right!.

As far as we are using the DP3T SDK I could refer to [this document](https://github.com/DP-3T/documents/blob/master/DP3T%20-%20Exposure%20Score%20Calculation.pdf). It's not recently updated but you could get some useful ideas from it.

Thanks.

**Comment by fsbaraglia** [comment]
nothing new, we can close the issue
