### ISSUE TITLE
isJailbroken exit

### ISSUE THREAD

**Issue by daviwiki** [RadarCOVID/radar-covid-ios#5]
I don't know if this was an app requirment but, a message to the user must be presented to let them know that the app not works with jailbreak devices.

This will be included into the AppDelegate instead of:

```
if JailBreakDetect.isJailbroken() {
     exit(-1)
}
```

**Comment by acalatrava** [comment]
In fact jailbreak detection should be disabled #12

**Comment by iCesofT** [comment]
Repeated #14 . We'll close this one.
