### ISSUE TITLE
Application localization should be inferred

### ISSUE THREAD

**Issue by alvaromb** [RadarCOVID/radar-covid-ios#6]
App should infer as many settings as possible, using the user configured localization instead of making the user to choose the language. Also, using `exit(0);` has been considered against best practices in iOS, as per [Apple's QA1561 Technical Q&A](https://developer.apple.com/library/archive/qa/qa1561/_index.html). Using standard localization strings is also being used in similar contact tracing apps, like [Swiss Covid](https://github.com/DP-3T/dp3t-app-ios-ch/tree/develop/Translations).

Is the team open to the following changes?

1. Infer user's language in language selector of `WelcomeViewController.swift`.
2. Use a more standard localization approach.

**Comment by iCesofT** [comment]
We get localisation strings from a service (see configuration server and Contentful), so we can change a text without upgrading the application. Also we can share strings between platforms (iOS / Android).
